#!/usr/bin/env python3
"""
Generate VERSION file with MD5 checksums for all tracked files.
Run this on your local machine BEFORE deploying.
Usage: python3 native/gen_version.py
"""
import hashlib
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Files to track (relative to project root)
TRACKED = [
    # "VERSION",  # excluded: self-MD5 impossible to get right
    "backend/app/main.py",
    "backend/app/config.py",
    "backend/app/database.py",
    "backend/app/__init__.py",
    "backend/app/models/__init__.py",
    "backend/app/models/device.py",
    "backend/app/models/device_template.py",
    "backend/app/models/dashboard.py",
    "backend/app/models/web_scraper.py",
    "backend/app/models/metrics.py",
    "backend/app/models/topology.py",
    "backend/app/models/rack.py",
    "backend/app/models/front_panel.py",
    "backend/app/models/alert.py",
    "backend/app/routers/__init__.py",
    "backend/app/routers/discovery.py",
    "backend/app/routers/devices.py",
    "backend/app/routers/device_models.py",
    "backend/app/routers/dashboards.py",
    "backend/app/routers/metrics.py",
    "backend/app/routers/topology.py",
    "backend/app/routers/racks.py",
    "backend/app/routers/front_panels.py",
    "backend/app/routers/alerts.py",
    "backend/app/routers/snmp_templates.py",
    "backend/app/routers/zabbix_templates.py",
    "backend/app/routers/mib_manager.py",
    "backend/app/routers/ai_settings.py",
    "backend/app/services/__init__.py",
    "backend/app/services/scanner.py",
    "backend/app/services/snmp_collector.py",
    "backend/app/services/zabbix_converter.py",
    "backend/app/services/zabbix_repo.py",
    "backend/app/services/icmp_monitor.py",
    "backend/app/services/topology_discovery.py",
    "backend/app/services/alert_engine.py",
    "backend/app/utils/__init__.py",
    "backend/app/utils/cidr.py",
    "backend/app/utils/snmp_helpers.py",
    "backend/app/utils/snmp_profiles.py",
    "backend/app/utils/mib_parser.py",
    "backend/app/websocket/__init__.py",
    "backend/app/websocket/manager.py",
    "backend/requirements.txt",
    "frontend/index.html",
    "frontend/js/app.js",
    "frontend/js/api.js",
    "frontend/js/websocket.js",
    "frontend/js/i18n.js",
    "frontend/js/utils/format.js",
    "frontend/js/utils/constants.js",
    "frontend/js/components/context-menu.js",
    "frontend/js/components/front-panel.js",
    "frontend/js/components/rack-view.js",
    "frontend/js/components/settings.js",
    "frontend/js/pages/dashboard.js",
    "frontend/js/pages/discovery.js",
    "frontend/js/pages/devices.js",
    "frontend/js/pages/device-detail.js",
    "frontend/js/pages/device-models.js",
    "frontend/js/pages/device-types.js",
    "frontend/js/pages/add-device.js",
    "frontend/js/pages/topology.js",
    "frontend/js/pages/racks.js",
    "frontend/js/pages/alerts.js",
    "frontend/js/pages/snmp-templates.js",
    "frontend/js/pages/zabbix-templates.js",
    "frontend/js/pages/mib-manager.js",
    "frontend/js/pages/settings-page.js",
    "frontend/js/utils/table-resize.js",
    "frontend/css/main.css",
    "frontend/css/dashboard.css",
    "frontend/css/discovery.css",
    "frontend/css/topology.css",
    "frontend/css/rack.css",
    "native/nms.sh",
    "native/nms.service",
    "native/init_db.sql",
    "native/nginx.conf",
]


def md5_file(path: Path) -> str:
    h = hashlib.md5()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()


def main():
    ver_path = ROOT / "VERSION"
    # Read current version (force UTF-8 for Windows compatibility)
    old_ver = "0.0.0"
    if ver_path.exists():
        first = ver_path.read_text(encoding="utf-8").strip().split("\n")[0].strip()
        if first: old_ver = first

    # Bump version (patch 00-99, rolls over to minor)
    parts = old_ver.split(".")
    major, minor, patch = int(parts[0]), int(parts[1]), int(parts[2]) + 1
    if patch > 99:
        minor += 1
        patch = 0
    new_ver = f"{major}.{minor}.{patch}"

    # Update index.html cache buster BEFORE computing MD5s
    html_path = ROOT / "frontend" / "index.html"
    if html_path.exists():
        html = html_path.read_text(encoding="utf-8")
        import re as _re
        html = _re.sub(r'\?v=[\d.]+"', f'?v={new_ver}"', html)
        html_path.write_text(html, encoding="utf-8")

    # Build manifest (VERSION excluded — self-MD5 is impossible to get right)
    lines = [new_ver, "# GENERATED BY gen_version.py — DO NOT EDIT", "# Files:"]
    missing = []
    ok = 0
    for f in sorted(TRACKED):
        p = ROOT / f
        if p.exists():
            md5 = md5_file(p)
            lines.append(f"{md5}  {f}")
            ok += 1
        else:
            lines.append(f"MISSING  {f}")
            missing.append(f)

    ver_path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    msg = f"VERSION {new_ver} - {ok} files hashed"
    if missing:
        msg += f", {len(missing)} MISSING: {missing}"
    else:
        msg += " [OK]"
    print(msg)


if __name__ == "__main__":
    main()
