"""baseline schema

Revision ID: fb2e278a066a
Revises: 
Create Date: 2026-09-14 22:03:10.944694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb2e278a066a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_settings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False, comment='openai, azure, local, deepseek, custom'),
    sa.Column('api_key', sa.String(length=500), nullable=False),
    sa.Column('api_base', sa.String(length=500), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('batch_size', sa.Integer(), nullable=False, comment='每轮AI分析的最大OID数量'),
    sa.Column('ai_concurrency', sa.Integer(), nullable=False, comment='AI分析并发批次数'),
    sa.Column('request_timeout', sa.Integer(), nullable=False, comment='单次AI请求超时(秒)'),
    sa.Column('group_timeout', sa.Integer(), nullable=False, comment='并发组超时(秒)'),
    sa.Column('test_concurrency', sa.Integer(), nullable=False, comment='SNMP测试并发数'),
    sa.Column('test_retries', sa.Integer(), nullable=False, comment='SNMP测试重试次数'),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dashboards',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_models',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('vendor', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('device_type', sa.String(length=50), nullable=False, comment='router, switch, firewall, server_linux, server_windows, other'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='network, server, custom'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('snmp_profile', sa.String(length=100), nullable=True, comment='key into snmp_profiles.py (legacy)'),
    sa.Column('template_type', sa.String(length=20), nullable=True, comment='snmp, mib, cisco, zabbix'),
    sa.Column('template_ref_id', sa.String(length=32), nullable=True, comment='ID of the selected template/MIB/list'),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('front_panels',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('device_model', sa.String(length=100), nullable=True),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('background_image', sa.String(length=500), nullable=True),
    sa.Column('ports_layout', sa.JSON(), nullable=True, comment='Overall layout config: orientation, port spacing, etc.'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mib_files',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False, comment='mib, cisco_list'),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('oid_count', sa.Integer(), nullable=False),
    sa.Column('mib_count', sa.Integer(), nullable=False),
    sa.Column('parsed_oids', sa.JSON(), nullable=True, comment='Parsed OID list from this MIB'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oid_test_results',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('oid', sa.String(length=500), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('result_value', sa.Text(), nullable=True),
    sa.Column('test_ip', sa.String(length=50), nullable=True),
    sa.Column('tested_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oid_test_results_oid'), 'oid_test_results', ['oid'], unique=False)
    op.create_table('parsed_oids',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('oid', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description_zh', sa.String(length=500), nullable=True),
    sa.Column('description_en', sa.String(length=500), nullable=True),
    sa.Column('mib_source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parsed_oids_oid'), 'parsed_oids', ['oid'], unique=True)
    op.create_table('racks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('height', sa.Integer(), nullable=False, comment='Rack height in RU (rack units)'),
    sa.Column('width', sa.Integer(), nullable=False, comment='Rack width in inches'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dashboard_widgets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('dashboard_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('widget_type', sa.String(length=20), nullable=False, comment='chart, gauge, table, text, stat, topn, number'),
    sa.Column('config', sa.JSON(), nullable=True, comment='Stores: metric_keys, device_ids, chart_type, refresh_interval, time_range, group_by, top_n, thresholds, ...'),
    sa.Column('position_x', sa.Integer(), nullable=False),
    sa.Column('position_y', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monitoring_templates',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('device_model_id', sa.String(length=32), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True, comment="Source of this template: 'manual', 'zabbix', 'mib'"),
    sa.Column('mib_file_ids', sa.JSON(), nullable=True, comment='JSON array of associated MIB file IDs'),
    sa.Column('cisco_list_ids', sa.JSON(), nullable=True, comment='JSON array of associated Cisco support list file IDs'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_model_id'], ['device_models.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devices',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('device_type', sa.String(length=50), nullable=False, comment='router, switch, firewall, server_linux, server_windows, other'),
    sa.Column('vendor', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('snmp_enabled', sa.Boolean(), nullable=False),
    sa.Column('snmp_version', sa.String(length=10), nullable=False),
    sa.Column('snmp_community', sa.String(length=100), nullable=True),
    sa.Column('snmp_port', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(length=20), nullable=False, comment='snmp, icmp, agent, web'),
    sa.Column('model_id', sa.String(length=32), nullable=True),
    sa.Column('template_id', sa.String(length=32), nullable=True, comment='Monitoring template'),
    sa.Column('snmp_template_id', sa.String(length=32), nullable=True, comment='SNMP template from templates page'),
    sa.Column('mib_file_id', sa.String(length=32), nullable=True, comment='Associated MIB file'),
    sa.Column('cisco_list_id', sa.String(length=32), nullable=True, comment='Associated Cisco support list'),
    sa.Column('zabbix_template_id', sa.String(length=32), nullable=True, comment='Associated Zabbix template'),
    sa.Column('agent_port', sa.Integer(), nullable=True),
    sa.Column('monitoring_interval', sa.Integer(), nullable=False),
    sa.Column('os_version', sa.String(length=100), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('ssh_port', sa.Integer(), nullable=True),
    sa.Column('rdp_port', sa.Integer(), nullable=True),
    sa.Column('web_port', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False, comment='online, offline, warning, unknown'),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('front_panel_id', sa.String(length=32), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['front_panel_id'], ['front_panels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['model_id'], ['device_models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['monitoring_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_ip_address'), 'devices', ['ip_address'], unique=False)
    op.create_table('template_items',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('template_id', sa.String(length=32), nullable=False),
    sa.Column('metric_name', sa.String(length=255), nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=False, comment='cpu, memory, disk, network, port, protocol, table, custom'),
    sa.Column('protocol', sa.String(length=20), nullable=False, comment='snmp, icmp, agent, web'),
    sa.Column('oid_or_key', sa.String(length=500), nullable=True),
    sa.Column('data_type', sa.String(length=20), nullable=False, comment='gauge, counter, table, text'),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('display_type', sa.String(length=20), nullable=False, comment='chart, gauge, text, table'),
    sa.Column('interval_seconds', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['monitoring_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert_rules',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('device_id', sa.String(length=32), nullable=True, comment='NULL means global rule for all devices'),
    sa.Column('metric_type', sa.String(length=50), nullable=False, comment='cpu, memory, disk, network'),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('condition', sa.String(length=5), nullable=False, comment='>, <, >=, <=, =='),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False, comment='info, warning, critical'),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_interfaces',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('device_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('if_index', sa.Integer(), nullable=True),
    sa.Column('if_type', sa.String(length=50), nullable=True),
    sa.Column('mac_address', sa.String(length=17), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True, comment='bps'),
    sa.Column('status', sa.String(length=10), nullable=False, comment='up, down, unknown'),
    sa.Column('alias', sa.String(length=255), nullable=True),
    sa.Column('last_change', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_interfaces_device_id'), 'device_interfaces', ['device_id'], unique=False)
    op.create_table('device_metrics',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('device_id', sa.String(length=32), nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=False, comment='cpu, memory, disk, network'),
    sa.Column('metric_name', sa.String(length=100), nullable=False, comment='e.g. cpu_usage, mem_total, disk_used_pct'),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_device_metric_name_time', 'device_metrics', ['device_id', 'metric_name', 'collected_at'], unique=False)
    op.create_index('idx_device_metric_time', 'device_metrics', ['device_id', 'metric_type', 'collected_at'], unique=False)
    op.create_index(op.f('ix_device_metrics_collected_at'), 'device_metrics', ['collected_at'], unique=False)
    op.create_index(op.f('ix_device_metrics_device_id'), 'device_metrics', ['device_id'], unique=False)
    op.create_table('device_ports',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('device_id', sa.String(length=32), nullable=False),
    sa.Column('port_name', sa.String(length=100), nullable=False),
    sa.Column('port_index', sa.Integer(), nullable=False),
    sa.Column('mac_address', sa.String(length=20), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('vlan', sa.Integer(), nullable=True),
    sa.Column('speed', sa.BigInteger(), nullable=True),
    sa.Column('duplex', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False, comment='up, down'),
    sa.Column('admin_status', sa.String(length=10), nullable=True),
    sa.Column('in_octets', sa.BigInteger(), nullable=True),
    sa.Column('out_octets', sa.BigInteger(), nullable=True),
    sa.Column('in_errors', sa.BigInteger(), nullable=True),
    sa.Column('out_errors', sa.BigInteger(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_device_ports_device_port_collected', 'device_ports', ['device_id', 'port_name', 'collected_at'], unique=False)
    op.create_table('device_protocol_data',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('device_id', sa.String(length=32), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False, comment='route, arp, dhcp, ndp, cdp, lldp, firewall_rules, nat_rules'),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_device_protocol_data_device_type_collected', 'device_protocol_data', ['device_id', 'data_type', 'collected_at'], unique=False)
    op.create_table('discovered_devices',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('vendor', sa.String(length=100), nullable=True),
    sa.Column('snmp_available', sa.Boolean(), nullable=False),
    sa.Column('snmp_community', sa.String(length=100), nullable=True),
    sa.Column('icmp_reachable', sa.Boolean(), nullable=False),
    sa.Column('discovery_method', sa.String(length=20), nullable=False),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.Column('mac_address', sa.String(length=17), nullable=True),
    sa.Column('os_type', sa.String(length=100), nullable=True),
    sa.Column('open_ports', sa.String(length=100), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('approved_device_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['approved_device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discovered_devices_ip_address'), 'discovered_devices', ['ip_address'], unique=False)
    op.create_table('rack_devices',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('rack_id', sa.String(length=32), nullable=False),
    sa.Column('device_id', sa.String(length=32), nullable=False),
    sa.Column('ru_position', sa.Integer(), nullable=False, comment='Starting RU position (1-based from top)'),
    sa.Column('ru_height', sa.Integer(), nullable=False, comment='Device height in RU'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rack_id'], ['racks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rack_devices_device_id'), 'rack_devices', ['device_id'], unique=False)
    op.create_index(op.f('ix_rack_devices_rack_id'), 'rack_devices', ['rack_id'], unique=False)
    op.create_table('topology_nodes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('device_id', sa.String(length=32), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('node_type', sa.String(length=20), nullable=False, comment='device, manual, text, image'),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('discovery_source', sa.String(length=20), nullable=False, comment='manual, auto, cdp, lldp'),
    sa.Column('canvas_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topology_nodes_device_id'), 'topology_nodes', ['device_id'], unique=False)
    op.create_table('web_scraper_configs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('device_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('selector_type', sa.String(length=20), nullable=False, comment='css, xpath, regex'),
    sa.Column('data_selector', sa.String(length=1000), nullable=False),
    sa.Column('metric_name', sa.String(length=255), nullable=False),
    sa.Column('refresh_interval', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('alert_rule_id', sa.String(length=32), nullable=True),
    sa.Column('device_id', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False, comment='info, warning, critical'),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alert_rule_id'], ['alert_rules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_alert_rule_id'), 'alerts', ['alert_rule_id'], unique=False)
    op.create_index(op.f('ix_alerts_device_id'), 'alerts', ['device_id'], unique=False)
    op.create_index(op.f('ix_alerts_triggered_at'), 'alerts', ['triggered_at'], unique=False)
    op.create_table('front_panel_ports',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('front_panel_id', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('port_type', sa.String(length=20), nullable=False, comment='rj45, sfp, sfp+, qsfp, qsfp28, console, usb, power'),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.Column('interface_id', sa.String(length=32), nullable=True),
    sa.Column('status_oid', sa.String(length=255), nullable=True, comment='Custom SNMP OID for port status if not linked to an interface'),
    sa.ForeignKeyConstraint(['front_panel_id'], ['front_panels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interface_id'], ['device_interfaces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_front_panel_ports_front_panel_id'), 'front_panel_ports', ['front_panel_id'], unique=False)
    op.create_table('interface_metrics',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('interface_id', sa.String(length=32), nullable=False),
    sa.Column('in_octets', sa.Integer(), nullable=True),
    sa.Column('out_octets', sa.Integer(), nullable=True),
    sa.Column('in_errors', sa.Integer(), nullable=True),
    sa.Column('out_errors', sa.Integer(), nullable=True),
    sa.Column('in_discards', sa.Integer(), nullable=True),
    sa.Column('out_discards', sa.Integer(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['interface_id'], ['device_interfaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_iface_metric_time', 'interface_metrics', ['interface_id', 'collected_at'], unique=False)
    op.create_index(op.f('ix_interface_metrics_collected_at'), 'interface_metrics', ['collected_at'], unique=False)
    op.create_index(op.f('ix_interface_metrics_interface_id'), 'interface_metrics', ['interface_id'], unique=False)
    op.create_table('topology_edges',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('source_node_id', sa.String(length=32), nullable=False),
    sa.Column('target_node_id', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('edge_type', sa.String(length=20), nullable=False, comment='wired, wireless, lag'),
    sa.Column('discovery_source', sa.String(length=20), nullable=False, comment='manual, auto, cdp, lldp'),
    sa.Column('source_interface', sa.String(length=100), nullable=True),
    sa.Column('target_interface', sa.String(length=100), nullable=True),
    sa.Column('line_style', sa.String(length=20), nullable=False, comment='solid, dashed, dotted'),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_node_id'], ['topology_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_node_id'], ['topology_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topology_edges')
    op.drop_index(op.f('ix_interface_metrics_interface_id'), table_name='interface_metrics')
    op.drop_index(op.f('ix_interface_metrics_collected_at'), table_name='interface_metrics')
    op.drop_index('idx_iface_metric_time', table_name='interface_metrics')
    op.drop_table('interface_metrics')
    op.drop_index(op.f('ix_front_panel_ports_front_panel_id'), table_name='front_panel_ports')
    op.drop_table('front_panel_ports')
    op.drop_index(op.f('ix_alerts_triggered_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_device_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_rule_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('web_scraper_configs')
    op.drop_index(op.f('ix_topology_nodes_device_id'), table_name='topology_nodes')
    op.drop_table('topology_nodes')
    op.drop_index(op.f('ix_rack_devices_rack_id'), table_name='rack_devices')
    op.drop_index(op.f('ix_rack_devices_device_id'), table_name='rack_devices')
    op.drop_table('rack_devices')
    op.drop_index(op.f('ix_discovered_devices_ip_address'), table_name='discovered_devices')
    op.drop_table('discovered_devices')
    op.drop_index('ix_device_protocol_data_device_type_collected', table_name='device_protocol_data')
    op.drop_table('device_protocol_data')
    op.drop_index('ix_device_ports_device_port_collected', table_name='device_ports')
    op.drop_table('device_ports')
    op.drop_index(op.f('ix_device_metrics_device_id'), table_name='device_metrics')
    op.drop_index(op.f('ix_device_metrics_collected_at'), table_name='device_metrics')
    op.drop_index('idx_device_metric_time', table_name='device_metrics')
    op.drop_index('idx_device_metric_name_time', table_name='device_metrics')
    op.drop_table('device_metrics')
    op.drop_index(op.f('ix_device_interfaces_device_id'), table_name='device_interfaces')
    op.drop_table('device_interfaces')
    op.drop_table('alert_rules')
    op.drop_table('template_items')
    op.drop_index(op.f('ix_devices_ip_address'), table_name='devices')
    op.drop_table('devices')
    op.drop_table('monitoring_templates')
    op.drop_table('dashboard_widgets')
    op.drop_table('racks')
    op.drop_index(op.f('ix_parsed_oids_oid'), table_name='parsed_oids')
    op.drop_table('parsed_oids')
    op.drop_index(op.f('ix_oid_test_results_oid'), table_name='oid_test_results')
    op.drop_table('oid_test_results')
    op.drop_table('mib_files')
    op.drop_table('front_panels')
    op.drop_table('device_models')
    op.drop_table('dashboards')
    op.drop_table('ai_settings')
    # ### end Alembic commands ###
